- hosts: anode
  remote_user: vibhu
  become: true
  vars:
    dict:
      msg_var: hiWelcome
      abc: alphabets
      lists: items
  tasks:  
  - name: DebugMessage
    debug:
      msg: "{{ hostvars[inventory_hostname].ansible_name | default('baba') }}"
  - name: DbugMessage
    debug:
      msg: "{{ hostvars[inventory_hostname]['mywork'] }}"
